### ISSUE TITLE
[백] 스프링에서 HTTPS 변경하기

### ISSUE THREAD

**Issue by Sangyong-Jeon** [YGUniv-NonSleep/Path#45]
# HTTPS로 변경하기
보안을 강화하기 위해 https로 변경한다.
먼저 인증서가 필요하다.

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/80039556/160085912-891c49e8-9cb2-4956-b428-27c633600906.png">

IntelliJ 터미널에서 임의의 키를 생성한다.
`keytool -genkey -alias spring -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 4000  `
위와 같이 명령어를 치면 비밀번호를 6자리 이상 입력하면 되는데 이것은 꼭 기억하자.
그 후 이름, 조직단위, 지역 등 입력하라고 나오는데 현재는 로컬이기에 아무거나 입력하면 된다.

<img width="778" alt="image" src="https://user-images.githubusercontent.com/80039556/160086237-a10b44dc-eb97-4ae3-b89d-f0411890c288.png">

그러면 생성이 끝난다.

<img width="945" alt="image" src="https://user-images.githubusercontent.com/80039556/160153015-2320c27d-8061-4e19-bcfc-2d144b4ce051.png">

`ls`를 터미널에 입력하면 `keystore.p12` 파일이 만들어진 것을 볼 수 있다.
이 상태에서 application.yml 파일에 다음과 같이 추가하자.
```
server:
  ssl:
    key-store: keystore.p12
    key-store-type: PKCS12
    key-store-password: 123456
    key-alias: spring
```

이 설정을 하고 나면 이제 모든 요청은 https로만 정상적으로 실행이 된다.
즉, `http://localhost:8080` 은 접속이 불가능하다.
